FROM python:3.10-slim

WORKDIR /app

# Install system dependencies and git
RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libglib2.0-0 \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


# Copier requirements_gradio.txt principal
COPY requirements_gradio.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements_gradio.txt

# Copy the application code
COPY . /app

# Expose Gradio port
EXPOSE 7860

# Immediate logging
ENV PYTHONUNBUFFERED=1

# Run the movie Gradio app
CMD ["python", "movie_gradio.py"]